### ISSUE TITLE
如何进行 伪静态

### ISSUE THREAD

**Issue by hb0730** [esme518/docker-maccms10#1]
Hei author 请问一下您有没有试过伪静态，该如何配置

**Comment by hb0730** [comment]
缺少[run a2enmod rewrite
](https://github.com/docker-library/php/issues/1373)

> 如需伪静态 
> 1. 先配置apache2.conf  `/etc/apache2/apache2.conf`
> ```conf
><Directory /var/www/html>
>        Options Indexes FollowSymLinks
>        AllowOverride All
>        Require all granted
></Directory>
> ```
> 2. 站点跟目录 添加 [.htaccess](https://github.com/magicblack/maccms10/blob/master/%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3/%E4%BC%AA%E9%9D%99%E6%80%81%E8%A7%84%E5%88%99/.htaccess)
> ```
><IfModule mod_rewrite.c>
>Options +FollowSymlinks -Multiviews
>RewriteEngine on
>
>RewriteCond %{REQUEST_FILENAME} !-d
>RewriteCond %{REQUEST_FILENAME} !-f
>RewriteRule ^(.*)$ index.php?/$1 [QSA,PT,L]
></IfModule>
>```
> 3. 后台配置 `系统> URL地址配置路由伪静态设置`
>  3.1 **开启**【路由状态】
>  3.2 **开启**【伪静态状态】

**Comment by muyiacc** [comment]
> 缺少[run a2enmod rewrite ](https://github.com/docker-library/php/issues/1373)
> 
> > 如需伪静态
> > 
> > 1. 先配置apache2.conf  `/etc/apache2/apache2.conf`
> > 
> > ```
> > <Directory /var/www/html>
> >        Options Indexes FollowSymLinks
> >        AllowOverride All
> >        Require all granted
> > </Directory>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. 站点跟目录 添加 [.htaccess](https://github.com/magicblack/maccms10/blob/master/%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3/%E4%BC%AA%E9%9D%99%E6%80%81%E8%A7%84%E5%88%99/.htaccess)
> > 
> > ```
> > <IfModule mod_rewrite.c>
> > Options +FollowSymlinks -Multiviews
> > RewriteEngine on
> > 
> > RewriteCond %{REQUEST_FILENAME} !-d
> > RewriteCond %{REQUEST_FILENAME} !-f
> > RewriteRule ^(.*)$ index.php?/$1 [QSA,PT,L]
> > </IfModule>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. 后台配置 `系统> URL地址配置路由伪静态设置`
> >    3.1 **开启**【路由状态】
> >    3.2 **开启**【伪静态状态】

静态设置后不生效的原因是 remoteip_module 没有启用，解决办法：
1. 进入容器
2. 启用 remoteip_module
```shell
a2enmod rewrite
```
3. 重启 apache
```shell
service apache2 restart
```
