### ISSUE TITLE
docker-maccms10 无法连接 redis 缓存服务

### ISSUE THREAD

**Issue by sinoserendipity** [esme518/docker-maccms10#2]
docker-maccms10 无法连接 redis 缓存服务，好像是php 缺少 php-redis 扩展，是否能在docker里增加这一php扩展

**Comment by esme518** [comment]
可以fork后自己添加 请参考[php官方镜像](https://hub.docker.com/_/php)
```
pecl install redis-5.3.7 \
&& docker-php-ext-enable redis
```
