### ISSUE TITLE
无法开启redis缓存，缺乏redis

### ISSUE THREAD

**Issue by muyiacc** [esme518/docker-maccms10#3]
使用docker仓库的最新镜像，我想开启redis缓存，提示缺乏扩展

我尝试在容器中安装redis扩展 `pecl install redis`，也有各种问题

结果出现了一系列的问题，

最后尝试源码安装，添加到 php.ini，去后台开启 redis ,还是出现 `模发生错误地请检查是否开启扩展库和配置项！`

以下为安装phpredis的步骤

1. 下载Redis扩展源码
首先，从Redis官方GitHub仓库下载最新版的Redis扩展源码。可以使用以下命令克隆仓库：
“`
git clone https://github.com/phpredis/phpredis.git
“`
2. 构建和安装扩展
进入到下载的源码目录，并执行以下命令进行构建和安装：
“`
cd phpredis
phpize
./configure
make
sudo make install
“`
3. 启用Redis扩展
打开php.ini文件，并添加以下内容：
“`
extension=redis.so
“`
保存并退出文件。
4. 重启Web服务器
为了使配置生效，需要重启Web服务器。可以使用以下命令重启Apache服务器：
“`
sudo service apache2 restart
“`

**Comment by esme518** [comment]
请fork本项目后自己添加
可以参考[php官方镜像](https://hub.docker.com/_/php)
```
pecl install redis-5.3.7 \
&& docker-php-ext-enable redis
```
